import { mkdirSync, writeFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import type { Agent } from '@deepseek-ai/dsh-agent'
import { ToolCallId } from '@deepseek-ai/dsh-llm'
import { createScope } from '@deepseek-ai/dsh-scope'
import { Session, SessionId } from '@deepseek-ai/dsh-session'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import ToolRuntime, { defineTool } from '@deepseek-ai/dsh-tools'
import { buildBaselineReport, markSize } from '../src/baseline.js'
import * as ProgressiveTools from '../src/index.js'

const signal = new AbortController().signal
const body = 'payload '.repeat(1_500)

async function measure(legacyResults: boolean): Promise<{ value: string; content: string }> {
  const ctx = new Context()
  await ctx.plugin(SystemPrompt, {})
  await ctx.plugin(ToolRuntime)
  ctx.tools.register(defineTool({
    name: 'browser_open',
    description: 'Open a page',
    parameters: { url: { type: 'string', required: true } },
    output: {
      schema: { type: 'string' },
      render: (_args, value) => [{ type: 'text', text: String(value) }],
    },
    execute: async () => body,
  }))
  await ctx.plugin(ProgressiveTools, {
    legacyResults,
    groups: [{ id: 'browser', include: ['browser_*'], description: 'Browser tools' }],
  })
  const session = Session.create(SessionId(`baseline-${legacyResults ? 'legacy' : 'current'}`))
  const agent = {} as Agent
  await ctx.plugin(Object.assign((inner: Context) => {
    Object.assign(agent, { id: session.id, session, ctx: createScope(inner, agent).ctx })
  }, { inject: ['tools', 'systemPrompt'] }))
  await ctx.systemPrompt.assemble({ scope: agent, agent, signal })
  await ctx.tools.execute({
    signal,
    callId: ToolCallId('search'),
    name: 'tool_search',
    arguments: { query: 'browser_open' },
    agent,
  })
  const dispatched = await ctx.tools.execute({
    signal,
    callId: ToolCallId('dispatch'),
    name: 'tool_dispatch',
    arguments: { name: 'browser_open', arguments: { url: 'https://example.test' } },
    agent,
  })
  if (dispatched.isError) throw new Error(dispatched.error.message)
  const content = dispatched.content.map(block => block.type === 'text' ? block.text : '').join('')
  return { value: JSON.stringify(dispatched.value), content }
}

function codeModeText(programReturn: string): string {
  return JSON.stringify({ logs: [], result: JSON.parse(programReturn) as unknown })
}

describe('deterministic volume baseline', () => {
  it('writes the character report and keeps the current program return smaller', async () => {
    const current = await measure(false)
    const legacy = await measure(true)
    const direct = markSize(body, 4)
    const currentProgram = markSize(codeModeText(current.value), 4)
    const legacyProgram = markSize(codeModeText(legacy.value), 4)
    expect(current.content).toBe(body)
    expect(currentProgram.characters).toBeLessThan(legacyProgram.characters)
    const report = buildBaselineReport({
      pluginVersion: '0.6.0',
      hostVersion: '0.1.7-rc.2',
      config: { mode: 'stable-proxy', legacyResults: false, resultBudget: false },
      catalogToolCount: 1,
      omittedDefinitionTokens: 1,
      requestText: body,
      charactersPerToken: 4,
      traces: [
        { kind: 'execution', parent: 'run_code', dispatcher: 'tool_dispatch', targetTool: 'browser_open', characters: currentProgram.characters },
        { kind: 'result', targetTool: 'browser_open', characters: direct.characters, note: 'direct model content' },
      ],
    })
    expect(report.requests[0]?.cost.reason).toBe('unknown')
    const directMark = markSize(current.content, 4)
    const lines = [
      '# Deterministic volume baseline',
      '',
      'Generated by `pnpm run baseline`. Counts are characters, bytes, and a',
      'character-ratio estimate. They are not provider tokens and not a bill.',
      'Server usage in this run is unknown. No model was called.',
      '',
      '| Path | Characters | Bytes | Estimated tokens |',
      '| --- | ---: | ---: | ---: |',
      `| Target body alone | ${direct.characters} | ${direct.bytes} | ${direct.estimatedTokens} |`,
      `| Direct dispatch model content | ${directMark.characters} | ${directMark.bytes} | ${directMark.estimatedTokens} |`,
      `| Current program return, whole object | ${currentProgram.characters} | ${currentProgram.bytes} | ${currentProgram.estimatedTokens} |`,
      `| Legacy program return, whole object | ${legacyProgram.characters} | ${legacyProgram.bytes} | ${legacyProgram.estimatedTokens} |`,
      '',
      'The current dispatch value does not include rendered content, so returning',
      'the whole program object does not repeat the body. The legacy envelope does.',
      'Direct model content stays the target rendering.',
      '',
      '```json',
      JSON.stringify(report, null, 2),
      '```',
      '',
    ]
    mkdirSync('docs', { recursive: true })
    writeFileSync('docs/cost-baseline-report.md', `${lines.join('\n')}\n`)
  })
})
